// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT4scJ75-GIlqf6eQqdWoO5BI2sgFi4-4',
    appId: '1:589458496221:android:1bb0efdf08e6461d5e9934',
    messagingSenderId: '589458496221',
    projectId: 'way-c10e7',
    storageBucket: 'way-c10e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKCK0VHO2fToq2GMTtFouXhc_6bTWcIE',
    appId: '1:589458496221:ios:432c7cb66c1186c95e9934',
    messagingSenderId: '589458496221',
    projectId: 'way-c10e7',
    storageBucket: 'way-c10e7.firebasestorage.app',
    androidClientId: '589458496221-7l37j9avqih3931b4es31a7g22kktcjl.apps.googleusercontent.com',
    iosClientId: '589458496221-7hb4a8mto1qh4rqsajvhu7cd6vjdqs5d.apps.googleusercontent.com',
    iosBundleId: 'com.digitcom.app',
  );

}